spring:
  application:
    name: dango-ai-code-supabase
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  cloud:
    nacos:
      server-addr: ${NACOS_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      config:
        namespace: ${NACOS_NAMESPACE:local}
  config:
    import:
      - nacos:dango-ai-code-supabase.yml?group=DEFAULT_GROUP&refreshEnabled=true
      - nacos:shared-dubbo.yml?group=SHARED_GROUP
      - nacos:shared-common.yml?group=SHARED_GROUP
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.dango.supabase.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
      - nacos:shared-supabase.yml?group=SHARED_GROUP
