spring:
  application:
    name: dango-ai-code-screenshot
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  cloud:
    nacos:
      server-addr: ${NACOS_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      config:
        namespace: ${NACOS_NAMESPACE:local}
  config:
    import:
      - nacos:dango-ai-code-screenshot.yml?group=DEFAULT_GROUP&refreshEnabled=true
      - nacos:shared-datasource.yml?group=SHARED_GROUP&refreshEnabled=true
      - nacos:shared-mybatis.yml?group=SHARED_GROUP
      - nacos:shared-cos.yml?group=SHARED_GROUP
      - nacos:shared-dubbo.yml?group=SHARED_GROUP
      - nacos:shared-common.yml?group=SHARED_GROUP
