spring:
  application:
    name: dango-ai-code-app
  profiles:
    active: local
  session:
    store-type: redis
    # session 10 年过期
    timeout: 315360000
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-cn-sn34m8htv0001kxo.rwlb.rds.aliyuncs.com:3306/dango_ai_code_mother
    username: dango
    password: A20203331040a
  main:
    allow-circular-references: true
server:
  port: 8124
  servlet:
    context-path: /api
    # cookie 10 年过期
    session:
      cookie:
        max-age: 315360000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.dango.dangoaicodeuser.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# Actuator 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
